---
title: "week 7"
author: "Kerui Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
data_matrix <- matrix(c(0.42, 0.12, 0.05, 0.28, 0.08, 0.05), nrow = 2, byrow = TRUE)
```

```{r}
colnames(data_matrix) <- c('1', '2', '3')
rownames(data_matrix) <- c('1', '2')
```

```{r}
data_df <- as.data.frame(data_matrix)
print(data_df)
```
```{r}

#Check if all number of between 0 and 1
is_valid_elements <- all(data_matrix >= 0 & data_matrix <= 1)


#Check if the sum = 1
is_valid_sum <- sum(data_matrix) == 1

#Verify the joint PMF
is_valid_pmf <- is_valid_elements && is_valid_sum

```


## Calculate the marginal distribution of X and Y and the corresponding marginal means.


```{r}

#Calculating Marginal distributions
marginal_X <- colSums(data_matrix)
marginal_Y <- rowSums(data_matrix)

#Calculate marginal sums
mu_X <- sum(as.numeric(colnames(data_matrix)) * marginal_X)
mu_Y <- sum(as.numeric(rownames(data_matrix)) * marginal_Y)
#calculate marginal variances
var_X <- sum((as.numeric(colnames(data_matrix)) - mu_X)^2 *marginal_X)
var_Y <- sum((as.numeric(rownames(data_matrix)) - mu_Y)^2 *marginal_Y)


c(marginal_X, marginal_Y, mu_X, mu_Y, var_X, var_Y)
```
### Calculate the correlation between X and Y.

The correlation of X and Y is given by (COV(x,y)) / S.Dx * S.Dy


COV(x,y)  = E(XY) - mu_X mu_Y 

```{r}



E_XY = 0
```

### Calculate P({X> 1}) | {Y < 2}). Are X and Y independent?



```{r}

# First find P(Y <2)
PY_less_than_2 <- sum(data_matrix[1,])

# Calulate P( X > 1| Y < 2)
PX_given_Y_1_2 <- sum(data_matrix[1, 2:3]) / PY_less_than_2

PX_given_Y_1_2

```
X and Y are not independent because they're joint probabilities.

# Question 2:


 A local bank decides whether a person can take a loan based on their income and credit score. The weekly income of the people in the town is distributed with a mean of 1000 and stdev of 250. The credit score of people in the sam town also follows a distribution with a mean of 700 and the standard dev is 36. Suppose the correlation between credit score and weekly income is 0.2.
 
 
 
 
 The bank creates an index to assess its customers’ profile. The index is the sum of 30% of
weekly income and 70% of credit score: I1 = 0.3 Income + 0.7 Credit Score. calculate the
expected value and the standard deviation of the index for people in this town



Note that expected value is linear:

E(I1) = E( 0.3 x income  + 0.7 x Credit score)


```{r}

E_In = 1000
E_cr = 700
E_l1 = 0.3*E_In + 0.7*E_cr

E_l1
```


Var(I1) = Var(0.3X + 0.7Y)
= Var(0.3x) + Var(0.7Y) + 2 cov(0.3X, 0.7Y)
=  0.3^2Var(X) + 0.7^2Var(Y) + 20.3* 0.7 *cov(X,Y)

cov(X,Y) = sd(X) * Sd(y) *2

```{r}

```




